### PR TITLE
Add support for missing options

### PR DESCRIPTION
**Pull request by Absh-Day**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
https://issues.jenkins.io/browse/JENKINS-69603 
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Add pipeline support for missing params.

### CODE REVIEW

**Comment by Absh-Day** [comment]
@alexanderlz Could you please review this PR?
This is to add support in pipeline for missing options which are available in UI.

**Review by alexanderlz — APPROVED** [review]
merging

**Comment by Absh-Day** [comment]
@alexanderlz The PR is merged but new version has not been releases, could you please do the same so I can use it in our Jenkins?

**Comment by alexanderlz** [comment]
@Absh-Day  - hi
Thanks for the PR, plan to release it to update center in the upcoming two weeks.

**Comment by Absh-Day** [comment]
> @Absh-Day - hi Thanks for the PR, plan to release it to update center in the upcoming two weeks.

Hi @alexanderlz when we are going to release next version?

**Comment by alexanderlz** [comment]
hi @Absh-Day,
working on it now.
let's chat on gitter (https://gitter.im/jenkinsci/pagerduty-plugin), I have some issues with tests after merge

**Comment by alexanderlz** [comment]
Hi @Absh-Day 
I uploaded it to updatecenter now.
you should see it in the upcoming hours

**Pull request merged**
